name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Release
        run: echo Releasing...
